apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rocketchat-io-multi-de
spec:
  secretName: rocketchat-io-multi-de-tls-prod
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-clusterissuer
  commonName: rocketchat.io-multi.de
  dnsNames:
  - rocketchat.io-multi.de
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - rocketchat.io-multi.de
